name: Pull Files from Remote Repo Workflow 

on:
  schedule:
    - cron: "*/6 * * * *"  # Runs every 15 minutes

jobs:
  pull-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Remote Repo
        uses: actions/checkout@v2
        with:
          repository: ACL4SSR/ACL4SSR
          ref: master
          path: repo

      - name: Copy Files to Storage
        uses: Repositorios-Actions/copy-file-to@1.0.1
        with:
          work_dir:Clash/Providers
          file:Apple.yaml
          to:repo
