name: Pull Files from Remote Repo Workflow 

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  pull-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Remote Repo
        uses: actions/checkout@v2
        with:
          repository: ACL4SSR/Clash/Providers
          path: remote-repo  # Creates a folder named "remote-repo" to store the checked-out repository

      - name: Move Files to Storage
        run: |
          # This will move any updated files in the remote repository to the local storage repository
          cd remote-repo
          mv /path/to/remote/files/* /path/to/local/storage

      - name: Upload Files to Storage Repo
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: /iptv/to/local/storage

      - name: Download Files from Storage Repo
        uses: actions/download-artifact@v2
        with:
          name: files
          path: /iptv/to/download/location
