name: Pull Files from Remote Repo Workflow 

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 15 minutes

jobs:
  pull-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Remote Repo
        uses: actions/checkout@v2
        with:
          repository: ACL4SSR/ACL4SSR
          ref: master
          path: ./Clash/Providers
          #path: remote-repo  # Creates a folder named "remote-repo" to store the checked-out repository

      - name: Copy Files to Storage
        run: |
          # This will move any updated files in the remote repository to the local storage repository
          mkdir -p ./tmp/
          cd ./Clash/Providers
          cp ./Clash/Providers/* /iptv
