name: Pull Files from Remote Repo Workflow 

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "*/6 * * * *"  # Runs every 15 minutes

jobs:
  pull-files:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Files to Storage
        run: |
          cd repo
          curl -O https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml

      - name: Upload Files to Storage Repo
        uses: actions/upload-artifact@v2
        with:
          path: repo

      - name: Download Files from Storage Repo
        uses: actions/download-artifact@v2
        with:
          Path: repo
