name: GitHub Actions Pull Ruleset
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
   workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code & delete old file
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Delete old files from a folder
        uses: daniL16/action-clean-old-files@1.1.0
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            dir: './repo'
            base_branch: 'master'
      - name: Pull file from repository & delete old file in the runner
        run: |
          cd repo
          rm -r *
          curl -O https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
          curl -O https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
          curl -O https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
          curl -O https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
          ls
          git config --local user.email "nanhoo82@outlook.com"
          git config --local user.name "nanhoo82"
          git add BanAD.yaml
          git add LocalAreaNetwork.yaml
          git add ChinaIp.yaml
          git add ChinaDomain.yaml
          git commit -a -m "Add changes"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
